name = "CustomPaper"
license = "MIT"
licenselink = "https://github.com/binhonglee/CustomPaper/blob/main/LICENSE"
description = "A customized forked version of Paper"
homepage = "https://github.com/binhonglee/CustomPaper/"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "binhonglee"
  homepage = "https://binhong.me/"

[original]
  name = "paper"
  homepage = "https://github.com/nanxiaobei/hugo-paper"
  repo = "https://github.com/nanxiaobei/hugo-paper"
